name: iapetus_meta
description: Tools to help with package:iapetus development, including JSON API message analysis and code generation APIs.
version: 0.1.0
homepage: https://github.com/EpimetheusMusicPlayer/iapetus_meta

publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  meta: ^1.8.0
  iapetus:
    path: ../iapetus
  json_annotation: ^4.5.0
  code_builder:
    git:
      url: https://github.com/hacker1024/code_builder.git
      ref: 7fa1ac26e526763e4cc70c4345b514bb830c78c8
  dart_style: ^2.2.3
  recase: ^4.0.0

dev_dependencies:
  lint: ^1.8.2
